### PR TITLE
Update JS, add JSX

### PR DESCRIPTION
**Pull request by revin**
Hi all, thanks for the great package! Here's a bit of work that updates the JavaScript syntax support to the latest version, and also adds support for highlighting JSX files.

If you'd rather me do this in two separate PRs, let me know 👍

### CODE REVIEW

**Comment by bcoe** [comment]
@revin this looks good; I think once it lands it would be neat to add a test to `marky-markdown` that exercises the JSX syntax.

I'm happy to land and release this, but would like to wait for confirmation from someone on the Atom team before I do so (CC: @zeke, @kevinsawicki).

**Comment by zeke** [comment]
Looks good to me 👍 

> would like to wait for confirmation from someone on the Atom team

I notice this is the first language pack that's outside of the `atom` org. That's not necessarily a problem, but worth noting. Maybe @orktes would want to move it to the atom org if they're game? I'm not actually sure what the vetting process is for those repos. cc @BinaryMuse @as-cii

>  it would be neat to add a test to marky-markdown that exercises the JSX syntax.

I agree, especially given the above third-party language question.

**Comment by revin** [comment]
oh interesting, I didn't notice that this would be the first non-`atom` one. If y'all decide we're better off using it separately in marky-markdown, that's cool with me.

The language highlighting tests in marky-markdown aren't particularly thorough; my work-in-progress PR over there has some basic ones that go with the grain of the existing tests, but as you can see in https://github.com/npm/marky-markdown/pull/396/commits/2101badf555f46512ec4b04f1b0905a47f0d0132 they're more along the lines of did-this-at-least-not-crash than did-this-do-the-exact-right-thing

**Comment by zeke** [comment]
👍

**Pull request merged**
