### PR TITLE
fix: update first-mate

### LINKED ISSUE #46: support node 6
now that first-mate has updated its oniguruma dep, once https://github.com/atom/highlights/pull/44 is merged, this should work fine on Node 6. 

change required: add 6 to `.travis.yml`

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #46 and #40

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
ok nevermind, my local copy just seems messed up. hey @bcoe could i get a review?

**Comment by ashleygwilliams** [comment]
just to note: my local tests fail 6 times, expects `class="source coffee"` gets `class="text plain null-grammar"` for each

**Comment by zeke** [comment]
> my local tests fail 6 times

Hmm I wonder why it's not failing on Travis. I will run it locally too. Are you using node 6, @ashleygwilliams?

**Comment by ashleygwilliams** [comment]
@zeke i tested with 4, 5, and 6

**Comment by bcoe** [comment]
@ashleygwilliams, unless @zeke tests/lands first, I'll also happily run this on a few node versions tonight, and release to a `next` branch so that we can run our smoke-test follower against it.

**Comment by zeke** [comment]
I'm getting the following errors on node 6.3.1:

```
Running "shell:test" (shell) task
....FF..F....FF..F
````

All the output: https://gist.github.com/zeke/bb13e228ba2b1ec3f6b7bc5020524ad3

**Comment by ashleygwilliams** [comment]
this is the exact same problem i'm having @zeke. wonder why travis isn't catching it?

**Comment by bcoe** [comment]
@ashleygwilliams @zeke tests are looking great on my end:

https://gist.github.com/bcoe/3349791bc03ae6df3df0d86ea8decc87

I did have to submodule init, and `./node_modules/.bin/grunt prepublish`; I know @ashleygwilliams tried this yesterday, and was still running into trouble -- I'm confused.

**Pull request merged**
