### PR TITLE
feat: upgrade language-javascript to v0.119.0 release

### PR DESCRIPTION
**Pull request by bcoe**
this upgrades the atom-language-javascript dependency to the latest release:

https://github.com/atom/language-javascript/releases/tag/v0.119.0

Addresses https://github.com/atom/highlights/pull/34

### CODE REVIEW

**Comment by bcoe** [comment]
@kevinsawicki I'm going to ask for forgiveness rather than permission and land this for us, this will help get npmjs.com rendering ES2015 JavaScript 👍

**Comment by bcoe** [comment]
@kevinsawicki while I've got your attention, any objection to me adding a CHANGELOG for this project, and updating a few of the dev dependencies?

**Comment by kevinsawicki** [comment]
> any objection to me adding a CHANGELOG for this project, and updating a few of the dev dependencies?

Sounds great, go for it 👍

**Comment by zeke** [comment]
👏

**Pull request merged**
